# Generated by Django 5.0.3 on 2024-08-26 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_house_listing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingwatch', to=settings.AUTH_USER_MODEL),
        ),
    ]
