# Generated by Django 5.0.3 on 2024-09-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(default=0, max_length=100)),
                ('listb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingbid', to='auctions.listing')),
                ('userb', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
